version: 2

models:
    - name: fact_divvy_rides
      description: >
        Unique divvy ride trips from 4/1/2020 through the previous month. Any records with a blank start_station_name
        or end_station_name have been removed. This model also excludes the columns for start_station_id and 
        end_station_id.
      columns:
          - name: ride_id
            description: Unique identifier for each Divvy Bike Rental
            tests:
                - unique:
                    severity: warn
                - not_null:
                    severity: warn
          - name: rideable_type 
            description: > 
                A code indicating if the rider is a member or paid with credit card
                member = Divvy Member
                casual = Paid with Credit Card
          - name: started_at 
            description: The date and time when the bike was rented.
          - name: ended_at 
            description: The date and time when bike was returned to a docking station.
          - name: start_station_name
            description: Name of the docking station the bike was rented from.
          - name: end_station_name
            description: Name of the docking station the bike was returned to.
          - name: start_lat
            description: Latitude coordinate of bike when rented
          - name: start_lng
            description: Longitude coordinate of bike when rented
          - name: end_lat
            description: Latitude coordinate of bike when returned
          - name: end_lng
            description: Longitude coordinate of bike when returned
          - name: start_day
            description: Day of the week the trip was started on
          - name: end_day
            description: Day of the week the trip ended on

    - name: divvy_trips_by_day
      description: > 
        Aggregated counts of trips perday over entire dataset
      columns:
          - name: trip_count
            description: Number of trips taken on the day.
          - name: member_casual
            description: A code indicating if the rider is a member or paid with credit card
              <br>member = Divvy Member
              <br>casual = Paid with Credit Card
          - name: day
            description: Day of the week

 